Algoritmo "exec2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   :ler o nome e dar boas vindas
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/12/2024
Var
// Seção de Declarações das variáveis 
nome:caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite seu nome: ")
leia (nome)
Escreva ("ola ",nome," seja bem vindo!")

Fimalgoritmo